name: Build PDF

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
      - name: Generate PDF
        uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: resume.pdf
      - name: Commit and push PDF
        run: git config user.name IsaacIngram
        run: git config user.email me@isaacingram.dev
        run: git add .
        run: git commit -m "(Auto) Commit generated PDF"
        run: git push
